version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: $APP_BITCOIN_IP
      APP_PORT: 3005
    container_name: bitcoin_app_proxy_1
  server:
    image: >-
      getumbrel/umbrel-bitcoin:v0.7.0@sha256:f2bb98c962fbad13991ceeda1308bbfaca13cc7cd5cb7d6b2e0d1d06e6123072
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/app:/data
      - ${APP_BITCOIN_DATA_DIR}:/bitcoin/.bitcoin
    environment:
      PORT: '3005'
      BITCOIN_HOST: bitcoin.friendspool.club
      RPC_PORT: '8085'
      BITCOIN_RPC_PORT: '8085'
      RPC_USER: your_rpc_user
      BITCOIN_RPC_USER: your_rpc_user
      RPC_PASSWORD: your_rpc_pass
      BITCOIN_RPC_PASSWORD: your_rpc_pass
      BITCOIN_RPC_HIDDEN_SERVICE: ${APP_BITCOIN_RPC_HIDDEN_SERVICE}
      BITCOIN_P2P_HIDDEN_SERVICE: ${APP_BITCOIN_P2P_HIDDEN_SERVICE}
      BITCOIN_P2P_PORT: ${APP_BITCOIN_P2P_PORT}
      DEVICE_DOMAIN_NAME: ${DEVICE_DOMAIN_NAME}
      BITCOIN_DEFAULT_NETWORK: ${BITCOIN_DEFAULT_NETWORK:-mainnet}
      BITCOIN_INITIALIZE_WITH_CLEARNET_OVER_TOR: ${BITCOIN_INITIALIZE_WITH_CLEARNET_OVER_TOR:-unset}
      BITCOIND_IP: bitcoin.friendspool.club
      TOR_PROXY_IP: ${APP_BITCOIN_TOR_PROXY_IP}
      TOR_PROXY_PORT: '9050'
      TOR_PROXY_CONTROL_PORT: '9051'
      TOR_PROXY_CONTROL_PASSWORD: moneyprintergobrrr
      I2P_DAEMON_IP: ${APP_BITCOIN_I2P_DAEMON_IP}
      I2P_DAEMON_PORT: '7656'
    networks:
      default:
        ipv4_address: $APP_BITCOIN_IP
    container_name: bitcoin_server_1
  tor:
    image: >-
      getumbrel/tor:0.4.7.8@sha256:2ace83f22501f58857fa9b403009f595137fa2e7986c4fda79d82a8119072b6a
    user: '1000:1000'
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/torrc:/etc/tor/torrc:ro
      - ${TOR_DATA_DIR}:/data
    environment:
      HOME: /tmp
    networks:
      default:
        ipv4_address: ${APP_BITCOIN_TOR_PROXY_IP}
    container_name: bitcoin_tor_1
  i2pd_daemon:
    image: >-
      purplei2p/i2pd:release-2.44.0@sha256:d154a599793c393cf9c91f8549ba7ece0bb40e5728e1813aa6dd4c210aa606f6
    user: root
    command: '--sam.enabled=true --sam.address=0.0.0.0 --sam.port=7656 --loglevel=error'
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/i2pd:/home/i2pd/data
    networks:
      default:
        ipv4_address: ${APP_BITCOIN_I2P_DAEMON_IP}
    container_name: bitcoin_i2pd_daemon_1
networks:
  default:
    ipam:
      config:
        - subnet: 10.21.21.0/24
